export const FETCH_FEED_REQUEST = 'FETCH_FEED_REQUEST';
export const FETCH_FEED_SUCCESS = 'FETCH_FEED_SUCCESS';

export const FETCH_ARTIST_REQUEST = 'FETCH_ARTIST_REQUEST';
export const FETCH_ARTIST_SUCCESS = 'FETCH_ARTIST_SUCCESS';

export const FETCH_SONG_REQUEST = 'FETCH_SONG_REQUEST';
export const FETCH_SONG_SUCCESS = 'FETCH_SONG_SUCCESS';

export const UPDATE_ARTIST_SONGS = 'UPDATE_ARTIST_SONGS';

export const ON_PAUSE = 'ON_PAUSE';
export const ON_PLAY = 'ON_PLAY';
export const ON_LOAD_START = 'ON_LOAD_START';
export const ON_TIME_UPDATE = 'ON_TIME_UPDATE';
export const ON_LOADED_METADATA = 'ON_LOADED_METADATA';
export const PLAY_SONG = 'PLAY_SONG';
